version: '3'

services:

  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.2
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "5601:5601"

  zookeeper:
    # ten image, neu khong ton tai se tu pull ve
    image: zookeeper
    # ten cua container
    container_name: zookeeper
    # truong hop khoi dong lai: no, always, on-failure, unless-stopped
    restart: always
    ports: 
      - "2181:2181"
    # extra_hosts:
    #   - "nimbus:127.0.0.1"
    #   - "zookeeper:127.0.0.1"
    #   - "supervisor1:127.0.0.1"
    #   - "supervisor2:192.168.1.171"

  nimbus:
    image: storm
    container_name: nimbus
    # ten cua host export ra
    hostname: nimbus
    # lenh chay
    command: storm nimbus -c storm.local.hostname=nimbus
    # the hien su rang buoc, chay zookeeper truoc
    depends_on:
      - zookeeper
    # lien ket vao 1 cum, o day se chay nimbus va zookeeper cung 1 hostname
    links:
      - zookeeper
    restart: always
    # cong su dung
    ports:
      - 6627:6627
    # ten mien xuat ra
    # extra_hosts:
    #   - "nimbus:127.0.0.1"
    #   - "zookeeper:127.0.0.1"
    #   - "supervisor1:127.0.0.1"
    #   - "supervisor2:192.168.1.171"

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    hostname: supervisor1
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - 6700:6700
      - 6701:6701
      - 6702:6702
      - 6703:6703
    extra_hosts:
    #   - "nimbus:127.0.0.1"
    #   - "zookeeper:127.0.0.1"
    #   - "supervisor1:127.0.0.1"
      - "supervisor2:192.168.1.8"

  ui:
    image: storm
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - 8080:8080
  
  # logger:
  #   image: storm
  #   container_name: logger
  #   command: storm logviewer
  #   depends_on:
  #     - nimbus
  #     - zookeeper
  #     - ui
  #   links:
  #     - nimbus
  #     - zookeeper
  #     - ui
  #   restart: always
  #   ports:
  #     - 8000:8000

volumes:
  esdata: